/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as ApiLessonAudioRouteImport } from './routes/api/lesson-audio'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AuthenticatedExamExamIdRouteImport } from './routes/_authenticated/exam.$examId'
import { Route as AuthenticatedExamNewRouteImport } from './routes/_authenticated/exam.new'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback.index'
import { Route as AuthenticatedFeedbackIdRouteImport } from './routes/_authenticated/feedback.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiLessonAudioRoute = ApiLessonAudioRouteImport.update({
  id: '/api/lesson-audio',
  path: '/api/lesson-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExamExamIdRoute = AuthenticatedExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamNewRoute = AuthenticatedExamNewRouteImport.update({
  id: '/exam/new',
  path: '/exam/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbackIdRoute = AuthenticatedFeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/api/lesson-audio': typeof ApiLessonAudioRoute
  '/shared/$token': typeof SharedTokenRoute
  '/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/exam/new': typeof AuthenticatedExamNewRoute
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/feedback/': typeof AuthenticatedFeedbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/api/lesson-audio': typeof ApiLessonAudioRoute
  '/shared/$token': typeof SharedTokenRoute
  '/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/exam/new': typeof AuthenticatedExamNewRoute
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/api/lesson-audio': typeof ApiLessonAudioRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_authenticated/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/_authenticated/exam/new': typeof AuthenticatedExamNewRoute
  '/_authenticated/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/stats'
    | '/api/lesson-audio'
    | '/shared/$token'
    | '/exam/$examId'
    | '/exam/new'
    | '/feedback/$id'
    | '/feedback/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/stats'
    | '/api/lesson-audio'
    | '/shared/$token'
    | '/exam/$examId'
    | '/exam/new'
    | '/feedback/$id'
    | '/feedback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/stats'
    | '/api/lesson-audio'
    | '/shared/$token'
    | '/_authenticated/exam/$examId'
    | '/_authenticated/exam/new'
    | '/_authenticated/feedback/$id'
    | '/_authenticated/feedback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiLessonAudioRoute: typeof ApiLessonAudioRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/lesson-audio': {
      id: '/api/lesson-audio'
      path: '/api/lesson-audio'
      fullPath: '/api/lesson-audio'
      preLoaderRoute: typeof ApiLessonAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/exam/$examId': {
      id: '/_authenticated/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof AuthenticatedExamExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/new': {
      id: '/_authenticated/exam/new'
      path: '/exam/new'
      fullPath: '/exam/new'
      preLoaderRoute: typeof AuthenticatedExamNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/$id': {
      id: '/_authenticated/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof AuthenticatedFeedbackIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedExamExamIdRoute: typeof AuthenticatedExamExamIdRoute
  AuthenticatedExamNewRoute: typeof AuthenticatedExamNewRoute
  AuthenticatedFeedbackIdRoute: typeof AuthenticatedFeedbackIdRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedExamExamIdRoute: AuthenticatedExamExamIdRoute,
  AuthenticatedExamNewRoute: AuthenticatedExamNewRoute,
  AuthenticatedFeedbackIdRoute: AuthenticatedFeedbackIdRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiLessonAudioRoute: ApiLessonAudioRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
